services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gol_storybook
    working_dir: /usr/src/app
    command: sh -lc "yarn install --immutable && yarn storybook -p 6006 -h 0.0.0.0"
    ports:
      - "6006:6006"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - storybook_cache:/root/.cache
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true

  board_mfe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gol_board_mfe
    working_dir: /usr/src/app
    command: sh -lc "yarn install --immutable && VITE_API_URL=${VITE_API_URL:-http://localhost:8080} yarn workspace @gol/board-mfe build && yarn workspace @gol/board-mfe preview --host 0.0.0.0 --port 5177 --strictPort"
    ports:
      - "5177:5177"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true

  controls_mfe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gol_controls_mfe
    working_dir: /usr/src/app
    command: sh -lc "yarn install --immutable && VITE_API_URL=${VITE_API_URL:-http://localhost:8080} yarn workspace @gol/controls-mfe build && yarn workspace @gol/controls-mfe preview --host 0.0.0.0 --port 5178 --strictPort"
    ports:
      - "5178:5178"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true

  shell:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gol_shell
    working_dir: /usr/src/app
    command: sh -lc "yarn install --immutable && BOARD_REMOTE=http://localhost:5177/assets/remoteEntry.js CONTROLS_REMOTE=http://localhost:5178/assets/remoteEntry.js yarn workspace @gol/shell dev --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - BACKEND_URL=${BACKEND_URL:-http://backend:8080}
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    depends_on:
      - board_mfe
      - controls_mfe

volumes:
  storybook_cache: